### ISSUE TITLE
tutorial error

### ISSUE THREAD

**Issue by ab940917** [umich-cadre/HetSim-gem5#1]
Hi! When i running your tutorial (vertor_add), I'm getting following errors while running the **!python populate_init_queues.py** step.

Traceback (most recent call last):
  File "populate_init_queues.py", line 26, in <module>
    exec(define + " = int(params." + define + ")")
  File "<string>", line 1, in <module>
TypeError: int() argument must be a string or a number, not 'type'

I use python2.7.
Could you provide a solution? thank you.

**Comment by subhankarpal** [comment]
This is potentially a python2 issue because `exec` behaves differently between python2 and python3. Could you try running this with python3 instead?

**Comment by ab940917** [comment]
Thank you for your reply and help. I successfully pass your tutorial.
